function [png] = driving_pdf()
%BASIC_PDF Summary of this function goes here
%   Detailed explanation goes here
png.PN_name = 'Module 4 Driving';
png.set_of_Ps = {'pBussdriver', 'pOnRoute3', 'pOnRoute5',...
                 'pOnRoute6', 'preChange_pOnRoutex60',...
                 'postChange_pOnRoutex60', 'pBussRouteDone'};
png.set_of_Ts = {'tGenerator','tRoute3','tRoute5','tRoute6',...
                 'preChange_tRoutex60', 'postChange_tRoutex60',...
                 'tRoute3_complete','tRoute5_complete',...
                 'tRoute6_complete', 'preChange_tRoutex60_complete',...
                 'postChange_tRoutex60_complete'};
png.set_of_As = {'tGenerator', 'pBussdriver', 1,...
                'pBussdriver', 'tRoute3', 3,...
                'pBussdriver', 'tRoute5', 5,...
                'pBussdriver', 'tRoute6', 6,...
                'pBussdriver', 'preChange_tRoutex60', 10,...
                'pBussdriver', 'postChange_tRoutex60', 1,...
                'tRoute3', 'pOnRoute3', 1,...
                'tRoute5', 'pOnRoute5', 1,...
                'tRoute6', 'pOnRoute6', 1,...
                'preChange_tRoutex60', 'preChange_pOnRoutex60', 1,...
                'postChange_tRoutex60', 'postChange_pOnRoutex60', 1,...
                'pOnRoute3', 'tRoute3_complete', 1,...
                'pOnRoute5', 'tRoute5_complete', 1,...
                'pOnRoute6', 'tRoute6_complete', 1,...
                'preChange_pOnRoutex60', 'preChange_tRoutex60_complete', 1,...
                'postChange_pOnRoutex60', 'postChange_tRoutex60_complete', 1,...
                'tRoute3_complete', 'pBussRouteDone', 1,...
                'tRoute5_complete', 'pBussRouteDone', 1,...
                'tRoute6_complete', 'pBussRouteDone', 1,...
                'preChange_tRoutex60_complete', 'pBussRouteDone', 1,...
                'postChange_tRoutex60_complete', 'pBussRouteDone', 1,...
                };

