function [png] = routes_pdf()
%ROUTES_PDF Summary of this function goes here
%   Detailed explanation goes here
png.PN_name = 'Module 3 Routes';
png.set_of_Ps = {'pRoutes', 'pStartRoute', 'pLastStop',...
    'pArriveAtBusStop', 'pInCar', 'pVehicleParked'};
png.set_of_Ts = {'tDriveToBusStopBus', 'tDriveToBusStopCar',...
    'tChangeDriver','tTakeBusToParking','tTakeCarToParking'};
png.set_of_As = {'pRoutes','tDriveToBusStopBus', 1,...
                 'pRoutes','tDriveToBusStopCar', 1,...
                 'tDriveToBusStopBus', 'pStartRoute', 1,...
                 'tDriveToBusStopCar', 'pArriveAtBusStop',1,...
                 'pLastStop', 'tTakeBusToParking', 1,...
                 'pLastStop','tChangeDriver', 1,... 
                 'pArriveAtBusStop', 'tChangeDriver',1,...
                 'tChangeDriver', 'pStartRoute',1,...
                 'tChangeDriver', 'pInCar',1,...
                 'pInCar', 'tTakeCarToParking',1,...
                 'tTakeBusToParking', 'pVehicleParked',1,...
                 'tTakeCarToParking', 'pVehicleParked',1,...
                 
    };

