function [png] = driving_pdf()
%BASIC_PDF Summary of this function goes here
%   Detailed explanation goes here
png.PN_name = 'Module 4 Driving';
png.set_of_Ps = {'pBussdriver', 'pOnRoute2', 'pOnRoute4',...
                 'pOnRoute6', 'pOnRoutex60_preChange',...
                 'pOnRoutex60_postChange', 'pBussRouteDone'};
png.set_of_Ts = {'tGenerator','tRoute2','tRoute4','tRoute6',...
                 'tRoutex60_preChange', 'tRoutex60_postChange',...
                 'tRoute2_complete','tRoute4_complete',...
                 'tRoute6_complete', 'tRoutex60_prechange_complete',...
                 'tRoutex60_postChange_complete'};
png.set_of_As = {'tGenerator', 'pBussdriver', 1,...
                'pBussdriver', 'tRoute2', 1,...
                'pBussdriver', 'tRoute4', 1,...
                'pBussdriver', 'tRoute6', 1,...
                'pBussdriver', 'tRoutex60_preChange', 1,...
                'pBussdriver', 'tRoutex60_postChange', 1,...
                'tRoute2', 'pOnRoute2', 1,...
                'tRoute4', 'pOnRoute4', 1,...
                'tRoute6', 'pOnRoute6', 1,...
                'tRoutx60_preChange', 'pOnRoutex60_preChange', 1,...
                'tRoutex60_postChange', 'pOnRoutex60_postChange', 1,...
                'pOnRoute2', 'tRoute2_complete', 1,...
                'pOnRoute4', 'tRoute4_complete', 1,...
                'pOnRoute6', 'tRoute6_complete', 1,...
                'pOnRoutex60_preChange', 'tRoutex60_prechange_complete', 1,...
                'pOnRoutex60_postChange', 'tRoutex60_postChange_complete', 1,...
                'tRoute2_complete', 'pBussRouteDone', 1,...
                'tRoute4_complete', 'pBussRouteDone', 1,...
                'tRoute6_complete', 'pBussRouteDone', 1,...
                'tRoutex60_prechange_complete', 'pBussRouteDone', 1,...
                'tRoutex60_postChange_complete', 'pBussRouteDone', 1,...
                };

