function [png] = driving_pdf()
%BASIC_PDF Summary of this function goes here
%   Detailed explanation goes here
png.PN_name = 'Module 4 Driving';
png.set_of_Ps = {'pBussdriver', 'pOnRoute2', 'pOnRoute4',...
                 'pOnRoute6', 'pOnRoutex60beforeChange',...
                 'pOnRoutex60beforeChange'};
png.set_of_Ts = {'tGenerator','tRoute2','tRoute4','tRoute6',...
                 'tRoutex60beforeChange', 'tRoutex60beforeChange',...
                 'tRoute2complete','tRoute4complete',...
                 'tRoute6complete', 'tRoutex60before'};
end

